name: Make

on: [push, pull_request]

jobs:
  compile-hexapod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile
        uses: bazhenov/action-avr-make@v1.0
